language: node_js
node_js:
  - 0.8
  - 0.6

before_script:
  - coffee --compile -o lib src
  - coffee -j gamejam/script/main.js -c gamejam/src/gfx.coffee gamejam/src/keys.coffee gamejam/src/player.coffee gamejam/src/game.coffee
