language: node_js
node_js:
  - 0.8

before_script:
  - coffee --compile -o lib src
  - coffee -j gamejam/script/main.js -b -c gamejam/src/_utils.coffee gamejam/src/sound.coffee gamejam/src/gfx.coffee gamejam/src/keys.coffee gamejam/src/entities/ gamejam/src/blocks/ gamejam/src/particles/ gamejam/src/levels/ gamejam/src/screens/ gamejam/src/dialogs/ gamejam/src/game.coffee
