// Generated by CoffeeScript 1.4.0
(function() {
  var game, gfx;

  gfx = {
    init: function() {
      var canvas;
      canvas = document.querySelector("#game");
      this.ctx = canvas != null ? typeof canvas.getContext === "function" ? canvas.getContext("2d") : void 0 : void 0;
      return this.ctx != null;
    }
  };

  game = {
    init: function() {
      if (!gfx.init()) {
        alert("Could not set up game canvas!");
      }
    }
  };

  game.init();

}).call(this);
