// Generated by CoffeeScript 1.4.0
(function() {
  var fillAndStrokeARectangle, fillSomeText, game, gfx;

  gfx = {
    init: function() {
      var canvas;
      canvas = document.querySelector("#game");
      this.ctx = canvas != null ? typeof canvas.getContext === "function" ? canvas.getContext("2d") : void 0 : void 0;
      if (!this.ctx) {
        return false;
      }
      this.w = canvas.width;
      this.h = canvas.height;
      return true;
    },
    clear: function() {
      return this.ctx.clearRect(0, 0, this.w, this.h);
    }
  };

  game = {
    init: function() {
      if (!gfx.init()) {
        alert("Could not set up game canvas!");
        return;
      }
      return gfx.clear();
    }
  };

  game.init();

  fillAndStrokeARectangle = function() {
    var c;
    c = gfx.ctx;
    c.fillStyle = "orange";
    return c.fillRect(10, 10, 300, 80);
  };

  fillSomeText = function() {
    var c;
    c = gfx.ctx;
    c.fillStyle = "#202020";
    c.font = "14pt monospace";
    return c.fillText("Professor Digman-Rüdnner", 30, 50);
  };

  fillAndStrokeARectangle();

  fillSomeText();

}).call(this);
